#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker1"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "11ca135c6fe2428795d0146e6070d720" }
]

[assets]
directory = "./public"
